export const NAVBAR_ITEMS = {
  DASHBOARD: 'dashboard',
  CUSTOMERS: 'customers',
  NOTIFICATIONS: 'notifications',
  INVENTORY: 'inventory',
  WORKORDERS: 'workorders',
  JOBS: 'jobs',
  SUPPLIERS: 'suppliers',
  ACCOUNTS: 'accounts',
  ACCOUNTS_REPORTS: 'reports',
  EMPLOYEES: 'employees',
  EMP_ATTENDENCE: 'emp-attendence',
  PAYROLL: 'payroll',
  USERS: 'administration',
};
