import { WO_TYPES } from 'src/constants/workorder-types';

// SERVER URL
const IP_URL = import.meta.env.VITE_SERVER_URL;

// URIs
export const BACKEND_API = {
  // AUTHENTICATION API'S
  LOGIN: IP_URL + '/authentication/noAuth/login',
  LOGOUT: IP_URL + '/authentication/auth/logout',

  USER_REGISTER: IP_URL + '/user/supAuth/create',
  USERS: IP_URL + '/user/auth/all',

  CUSTOMERS: IP_URL + '/customer/auth/customers',
  CUSTOMER: IP_URL + '/customer/auth/customer',
  CUSTOMER_REGISTER: IP_URL + '/customer/auth/register',
  CUSTOMER_EDIT: IP_URL + '/customer/supAuth/update',

  VEHICLE_REGISTER: IP_URL + '/vehicle/auth/register',
  VEHICLE_EDIT: IP_URL + '/vehicle/supAuth/update',

  ITEMS: IP_URL + '/inventory/auth/items',
  ITEMS_SELECT: IP_URL + '/inventory/auth/items-select',
  ITEMS_ADD: IP_URL + '/inventory/auth/create',
  ITEMS_EDIT: IP_URL + '/inventory/supAuth/update',
  ITEM_UPDATE_STOCK: IP_URL + '/inventory/auth/update-stocks',
  ITEM_UPDATE_STOCK_BULK: IP_URL + '/inventory/auth/bulk-stock-update',
  ITEM_UPDATE_LOGS: IP_URL + '/inventory/auth/stock-logs',
  ITEMS_INFO: IP_URL + '/inventory/auth/item',
  ITEMS_STOCK_STATISTICS: IP_URL + '/inventory/auth/inv-stocks-status',

  WO_ALL: IP_URL + '/workorder/auth/list',
  WO_ACTIVE: IP_URL + '/workorder/auth/active-orders',
  WO_INFO: IP_URL + '/workorder/auth/info',
  WO_CREATE: IP_URL + '/workorder/auth/create',
  WO_UPDATE: IP_URL + '/workorder/auth/update',
  WO_ASSIGNEES: IP_URL + '/workorder/auth/assign-emp',
  WO_DOWNLOAD_INVOICE: IP_URL + '/workorder/auth/download-invoice',
  WO_UPDATE_COMPLETED: IP_URL + '/workorder/auth/update-complete',
  WO_UPDATE_CLOSED: IP_URL + '/workorder/auth/update-closed',
  WO_CUSTOMER: IP_URL + '/workorder/auth/customer-jobs',
  WO_CUSTOMER_PAYMENT_STATUS: IP_URL + '/workorder/auth/customer-payment-stats',
  WO_CHART_REVENUE: IP_URL + '/workorder/auth/stat-revenue-chart',
  WO_CHART_TOTAL_JOBS: IP_URL + '/workorder/auth/stat-total-jobs-chart',
  WO_TODAY_REVENUE: IP_URL + '/workorder/auth/today-revenue',
  WO_TOTAL_RECEIVABLES: IP_URL + '/workorder/auth/total-receivables',
  WO_ACTIVE_JOBS_COUNT: IP_URL + '/workorder/auth/total-active-jobs',

  PAYMENTS: IP_URL + '/payment/auth/payments',
  PAYMENTS_PENDING: IP_URL + '/payment/auth/pending-payments',
  PAYMENT_WO: IP_URL + '/payment/auth/wo-payments',
  PAYMENT_CREATE: IP_URL + '/payment/auth/add',
  PAYMENT_DELETE: IP_URL + '/payment/supAuth/delete-payment',
  PAYMENT_WO_DELETE: IP_URL + '/payment/supAuth/delete-wo-payment',
  PAYMENT_CREATE_EXP: IP_URL + '/payment/auth/add-expenses',
  PAYMENT_CREATE_INC: IP_URL + '/payment/auth/add-income',
  PAYMENT_CREATE_REFUND: IP_URL + '/payment/supAuth/refund-payment',
  PAYMENT_CREATE_GRN: IP_URL + '/payment/auth/grn-payment',
  PAYMENT_COMPLETE_RECORD: IP_URL + '/payment/auth/complete-payment',
  PAYMENT_GRN: IP_URL + '/payment/auth/grn-payments',
  PAYMENT_SUMMARY: IP_URL + '/payment/auth/summary',
  PAYMENT_FIN_SUMMARY: IP_URL + '/payment/auth/financial-summary',
  PAYMENT_EXPENSES_SUMMARY: IP_URL + '/payment/auth/expense-summary',
  PAYMENT_FINANCIAL_REPORT: IP_URL + '/payment//auth/generate-report',

  EMP_REGISTER: IP_URL + '/employee/auth/register',
  EMP_UPDATE: IP_URL + '/employee/supAuth/update',
  EMP_ALL: IP_URL + '/employee/auth/employees',
  EMP_INFO: IP_URL + '/employee/auth/employee',
  EMP_SELECT: IP_URL + '/employee/auth/selection',
  EMP_ATT_GET: IP_URL + '/employee/auth/attendence',
  EMP_ATT: IP_URL + '/employee/auth/emp-attendence',
  EMP_ATT_ADD: IP_URL + '/employee/auth/add-emp-attendence',
  EMP_WORKORDERS: IP_URL + '/workorder/auth/emp-jobs',

  SUPPLIERS: IP_URL + '/supplier/auth/suppliers',
  SUPPLIER_INFO: IP_URL + '/supplier/auth/info',
  SUPPLIER_ADD: IP_URL + '/supplier/auth/register',
  SUPPLIER_UPDATE: IP_URL + '/supplier/supAuth/update',
  SUPPLIER_OPTIONS: IP_URL + '/supplier/auth/select-suppliers',
  SUPPLIER_PURCHASES: IP_URL + '/supplier/auth/supplier-purchases',
  SUPPLIER_GRN_RECORDS: IP_URL + '/supplier/auth/grn',
  SUPPLIER_GRN_RECORD_INFO: IP_URL + '/supplier/auth/grn-info',
  SUPPLIER_PAYMENTS: IP_URL + '/supplier/auth/supplier-payments',
  SUPPLIER_ADD_PAYMENTS: IP_URL + '/supplier/auth/add-payment',
  SUPPLIER_ITEMS_INFO: IP_URL + '/supplier/auth/supplier-items',
  SUPPLIER_RETURNED_ITEMS: IP_URL + '/supplier/auth/return-records',
  SUPPLIER_RETURN_ITEM: IP_URL + '/supplier/auth/return-item',
  SUPPLIER_RETURN_UPDATE: IP_URL + '/supplier/supAuth/return-update',
  SUPPLIER_RETURN_PROCESS: IP_URL + '/supplier/auth/process-return',
  SUPPLIER_RETURN_CANCEL: IP_URL + '/supplier/auth/cancel-return',
};
